# Generated by Django 5.0.2 on 2024-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
