# Generated by Django 5.0.2 on 2024-09-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0004_document_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='documents/')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
