# Generated by Django 5.0.2 on 2024-09-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0005_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
