# Generated by Django 5.0.2 on 2024-09-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0007_remove_imageupload_description_imageupload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
