# Generated by Django 5.0.2 on 2024-09-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0008_alter_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
